version: 2.1
commands:
  checkout_and_install_aria2_deps:
    steps:
      - checkout
      - run:
          name: "Installing aria2 dependency package"
          command: >-
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
            sudo apt-mark hold openssh-server &&
            sudo apt-get update &&
            sudo apt-get upgrade &&
            sudo apt-get install -y software-properties-common libssh2-1-dev libc-ares-dev zlib1g-dev libsqlite3-dev pkg-config libssl-dev libexpat1-dev gcc g++ make cmake libcppunit-dev autoconf automake autotools-dev autopoint libtool libcurl4-openssl-dev libevent-dev ca-certificates build-essential intltool libgcrypt-dev libxml2-dev lzma liblzma-dev libicu-dev g++-7 &&
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 &&
            sudo update-alternatives --config gcc &&
            gcc --version &&
            g++ --version
      - run:
          name: "Before aria2 install checks"
          command: >-
            export CC=g++ &&
            $CC --version
jobs:
  non-static-build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout_and_install_aria2_deps
      - run:
          name: "Running auto re-configuring"
          command: 'autoreconf -i'
      - run:
          name: "Running auto make"
          command: 'automake'
      - run:
          name: "Running auto configuring"
          command: 'autoconf'
      - run:
          name: "Running configure"
          command: './configure CPPFLAGS=-fsanitize=address LDFLAGS="-fsanitize=address -fuse-ld=gold"'
  static-build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout_and_install_aria2_deps
      - run:
          name: "Running auto re-configuring"
          command: 'autoreconf -i'
      - run:
          name: "Running configure"
          command: './configure CPPFLAGS=-fsanitize=address LDFLAGS="-fsanitize=address -fuse-ld=gold" ARIA2_STATIC=yes'
      - run:
          name: "Running make"
          command: 'make'
      - run:
          name: "Running make install"
          command: 'sudo make install'
      - run:
          name: "aria2 size before stripping"
          command: 'ls -lah /usr/local/bin/aria2c'
      - run:
          name: "Copy artifacts to tmp folder"
          command: >-
            mkdir /tmp/artifacts &&
            cp /usr/local/bin/aria2c /tmp/artifacts/ &&
            strip -v /tmp/artifacts/aria2c
      - run:
          name: "aria2 size after stripping"
          command: 'ls -lah /tmp/artifacts/'
      - store_artifacts:
          path: /tmp/artifacts/aria2c
workflows:
  version: 2.1
  build:
    jobs:
      - non-static-build
      - static-build
