version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Installing aria2 dependency package"
          command: >-
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
            sudo apt-mark hold openssh-server &&
            sudo apt-get update &&
            sudo apt-get upgrade &&
            sudo apt-get -y install libssh2-1-dev libc-ares-dev zlib1g-dev libsqlite3-dev pkg-config libssl-dev libexpat1-dev gcc g++ make cmake libcppunit-dev autoconf automake autotools-dev autopoint libtool libcurl4-openssl-dev libevent-dev ca-certificates build-essential intltool libgcrypt-dev libxml2-dev lzma liblzma-dev libicu-dev
      - run:
          name: "Before aria2 install checks"
          command: >-
            export CC=g++ &&
            $CC --version
